CREATE TABLE applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_posting_id UUID NOT NULL,
    applicant_first_name VARCHAR(100) NOT NULL,
    applicant_last_name VARCHAR(100) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_phone VARCHAR(50),
    cv_url TEXT NOT NULL,
    cover_letter TEXT,
    portfolio_url TEXT,
    linkedin_url TEXT,
    current_location VARCHAR(255),
    desired_salary DECIMAL(12,2),
    notice_period VARCHAR(100),
    status VARCHAR(50) DEFAULT 'applied' CHECK (status IN ('applied',
    'screening',
    'shortlisted',
    'interview_scheduled',
    'interviewed',
    'offer_extended',
    'offer_accepted',
    'offer_rejected',
    'hired',
    'rejected',
    'withdrawn')),
    pipeline_stage VARCHAR(100) DEFAULT 'new_application',
    score INTEGER CHECK (score >= 0 AND score <= 100),
    notes TEXT,
    source VARCHAR(100),
    applied_at TIMESTAMP DEFAULT NOW(),
    last_updated_by UUID,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);