CREATE TABLE employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    employee_number VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    date_of_birth DATE,
    gender VARCHAR(20),
    address TEXT,
    city VARCHAR(100),
    country VARCHAR(100),
    postal_code VARCHAR(20),
    emergency_contact_name VARCHAR(255),
    emergency_contact_phone VARCHAR(50),
    date_hired DATE NOT NULL,
    employment_type VARCHAR(50) CHECK (employment_type IN ('full_time',
    'part_time',
    'contract',
    'temporary')),
    department VARCHAR(100),
    position VARCHAR(100),
    reporting_to UUID,
    salary_grade VARCHAR(50),
    visa_type VARCHAR(100),
    visa_expiry_date DATE,
    right_to_work_verified BOOLEAN DEFAULT false,
    right_to_work_expiry DATE,
    status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active',
    'on_leave',
    'suspended',
    'terminated')),
    termination_date DATE,
    termination_reason TEXT,
    created_by UUID NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);