CREATE TABLE generated_letters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL,
    employee_id UUID,
    application_id UUID,
    letter_type VARCHAR(100) NOT NULL,
    subject VARCHAR(500),
    content TEXT NOT NULL,
    pdf_url TEXT,
    status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft',
    'pending_approval',
    'approved',
    'sent',
    'rejected')),
    generated_by UUID NOT NULL,
    generated_at TIMESTAMP DEFAULT NOW(),
    approved_by UUID,
    approved_at TIMESTAMP,
    sent_at TIMESTAMP,
    recipient_email VARCHAR(255),
    metadata TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);