CREATE TABLE interviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id UUID NOT NULL,
    interview_type VARCHAR(50) CHECK (interview_type IN ('phone_screening',
    'video',
    'in_person',
    'technical',
    'final')),
    scheduled_date TIMESTAMP NOT NULL,
    duration INTEGER DEFAULT 60,
    location TEXT,
    meeting_link TEXT,
    interviewer_ids TEXT,
    status VARCHAR(50) DEFAULT 'scheduled' CHECK (status IN ('scheduled',
    'completed',
    'cancelled',
    'rescheduled',
    'no_show')),
    feedback TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    recommendation VARCHAR(50) CHECK (recommendation IN ('strong_hire',
    'hire',
    'maybe',
    'no_hire')),
    created_by UUID NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);