CREATE TABLE job_postings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_title VARCHAR(255) NOT NULL,
    job_code VARCHAR(50) UNIQUE,
    department VARCHAR(100) NOT NULL,
    location VARCHAR(255),
    employment_type VARCHAR(50) CHECK (employment_type IN ('full_time',
    'part_time',
    'contract',
    'temporary',
    'internship')),
    salary_range_min DECIMAL(12,2),
    salary_range_max DECIMAL(12,2),
    salary_currency VARCHAR(10) DEFAULT 'USD',
    job_description TEXT NOT NULL,
    responsibilities TEXT,
    requirements TEXT,
    qualifications TEXT,
    benefits TEXT,
    application_deadline DATE,
    status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft',
    'published',
    'closed',
    'cancelled')),
    published_at TIMESTAMP,
    closed_at TIMESTAMP,
    positions_available INTEGER DEFAULT 1,
    positions_filled INTEGER DEFAULT 0,
    created_by UUID NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);