CREATE TABLE leave_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL,
    leave_type VARCHAR(50) NOT NULL CHECK (leave_type IN ('annual',
    'sick',
    'unpaid',
    'maternity',
    'paternity',
    'compassionate',
    'other')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days DECIMAL(5,2) NOT NULL,
    reason TEXT,
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending',
    'approved',
    'rejected',
    'cancelled')),
    reviewed_by UUID,
    reviewed_at TIMESTAMP,
    review_notes TEXT,
    requested_at TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);